name: NASA Project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Nodejs version 19
        uses: actions/setup-node@v4
        with:
          node-version: "19"
      - run: npm install
      - run: npm run build --prefix client
